/** The candidate-facing mirror of what an agency's client-brief route
 *  (api/client-brief) generates about a pool candidate — same document
 *  shape, built from the candidate's own profile and their own Fit Score
 *  instead of an agency's ranking of them. Lets a candidate see exactly
 *  what a recruiter/hiring-manager-facing summary of them would say,
 *  before anyone else generates one. */

import type { CandidateProfile, JobDescription } from "../models";
import type { FitReport } from "../srs-models";

export function buildCandidateBrief(profile: CandidateProfile, job: JobDescription | null, fit: FitReport | null): string {
  return [
    "# Your client brief preview",
    "",
    "_This mirrors the same read-only summary an agency or recruiter would generate about you — see what it says before you share anything._",
    "",
    `**Name:** ${profile.name}`,
    profile.preferences.preferredRoles.length ? `**Preferred role:** ${profile.preferences.preferredRoles.join(", ")}` : "",
    profile.extractedSkills.length ? `**Key skills:** ${profile.extractedSkills.slice(0, 10).join(", ")}` : "",
    "",
    job ? `**Target job:** ${job.title} · ${job.companyName}` : "**Target job:** none selected — analyze a job on Step 2 to see your Fit Score here.",
    fit ? `**Fit Score:** ${Math.round(fit.score)}% (${fit.label})` : "",
    "",
    "## Strong areas",
    ...(fit
      ? [...fit.matches, ...fit.transferable].slice(0, 8).map((a) => `- ${a}`)
      : ["_No active job selected — nothing to evaluate against yet._"]),
    "",
    "## Gaps",
    ...(fit ? fit.gaps.slice(0, 8).map((g) => `- ${g}`) : []),
    "",
    "_Generated by ResumeProof — evidence only, nothing invented._"
  ]
    .filter(Boolean)
    .join("\n");
}
