import { NextResponse } from "next/server";
import { getAgencyActiveJob, getAgencyCandidatePool } from "@/lib/workspace-store";
import { bindWorkspaceUser } from "@/lib/auth/bind-workspace";
import { recordAuditEvent } from "@/lib/audit-log";
import { analyzeOne } from "@/lib/pipeline";

export const dynamic = "force-dynamic";

/** Read-only client brief for coaches/hiring managers — built from the
 *  agency's own selected pool candidate and their evidence-based fit
 *  against the active job. Previously ignored candidateId entirely and
 *  used the logged-in account's own seeker profile, which only made sense
 *  if the agency operator was also using the app as their own candidate. */
export async function GET(request: Request) {
  const userId = await bindWorkspaceUser();
  const { searchParams } = new URL(request.url);
  const candidateId = searchParams.get("candidateId");

  const pool = await getAgencyCandidatePool();
  const candidate = candidateId ? pool.find((c) => c.id === candidateId) : pool[0];
  if (!candidate) {
    return NextResponse.json(
      { error: candidateId ? "That candidate isn't in this account's pool." : "No candidate available." },
      { status: 400 }
    );
  }
  await recordAuditEvent(userId, "view", `candidate-brief:${candidate.id}`, candidate.name);

  const job = await getAgencyActiveJob();
  const evaluation = job ? analyzeOne(candidate, job) : null;

  const brief = [
    "# Client brief (read-only)",
    "",
    `**Name:** ${candidate.name}`,
    candidate.preferences.preferredRoles.length ? `**Preferred role:** ${candidate.preferences.preferredRoles.join(", ")}` : "",
    candidate.extractedSkills.length ? `**Key skills:** ${candidate.extractedSkills.slice(0, 10).join(", ")}` : "",
    "",
    job ? `**Active job:** ${job.title} · ${job.companyName}` : "**Active job:** none selected",
    evaluation ? `**Fit Score:** ${Math.round(evaluation.qualificationScore)}% (${evaluation.isShortlisted ? "Shortlisted" : "Not shortlisted"})` : "",
    evaluation ? `**Preference alignment:** ${evaluation.preferenceAlignment}` : "",
    "",
    "## Strong areas",
    ...(evaluation ? evaluation.strongAreas.slice(0, 8).map((a) => `- ${a}`) : ["_No active job selected — nothing to evaluate against yet._"]),
    "",
    "## Gaps",
    ...(evaluation?.missingRequirements || []).slice(0, 8).map((g) => `- ${g}`),
    "",
    "_Generated by ResumeProof — evidence only, nothing invented._"
  ]
    .filter(Boolean)
    .join("\n");

  return NextResponse.json({ brief, generatedAt: new Date().toISOString(), candidateId: candidate.id, candidateName: candidate.name });
}
