import { NextResponse } from "next/server";
import { getSeeker } from "@/lib/workspace-store";
import { vaultCompleteness } from "@/lib/engines/career-vault";

export const dynamic = "force-dynamic";

/** Read-only client brief for coaches — vault summary + fit, no fabrication. */
export async function GET() {
  const seeker = await getSeeker();
  const health = vaultCompleteness(seeker.vault);
  const job = seeker.activeJob;
  const fit = seeker.fit;

  const brief = [
    "# Client brief (read-only)",
    "",
    `**Name:** ${seeker.profile.name}`,
    `**Target role:** ${seeker.vault.targetRole || "—"}`,
    `**Vault completeness:** ${health.percent}% (${health.approvedCount} approved items)`,
    "",
    job ? `**Active job:** ${job.title} · ${job.companyName}` : "**Active job:** none analyzed",
    fit ? `**Fit Score:** ${fit.score}% (${fit.label})` : "",
    fit?.applyReadiness ? `**Apply readiness:** ${fit.applyReadiness.headline}` : "",
    "",
    "## Top evidence",
    ...seeker.vault.evidence
      .filter((e) => e.verificationStatus === "approved")
      .slice(0, 8)
      .map((e) => `- [${e.type}] ${e.content.slice(0, 120)}`),
    "",
    "## Gaps",
    ...(fit?.coreGaps || fit?.gaps || []).slice(0, 8).map((g) => `- ${g}`),
    "",
    "_Generated by ResumeProof — evidence only, nothing invented._"
  ]
    .filter(Boolean)
    .join("\n");

  return NextResponse.json({ brief, generatedAt: new Date().toISOString() });
}
